# Generated by Django 4.2.13 on 2024-07-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hash_extension', '0002_countermeasure'),
    ]

    operations = [
        migrations.AddField(
            model_name='countermeasure',
            name='sha385',
            field=models.BooleanField(default=False),
        ),
    ]
