# Generated by Django 4.1.13 on 2024-07-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hash_extension', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hmac', models.BooleanField(default=False)),
            ],
        ),
    ]
