# Generated by Django 4.1.13 on 2024-07-30 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hash_extension', '0002_countermeasure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CounterMeasure',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
